from alembic import op
import sqlalchemy as sa
revision='001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('email',sa.String(320),nullable=False),sa.Column('password_hash',sa.String(512),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('is_email_verified',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now())); op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_table('lectures',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('owner_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('title',sa.String(255),nullable=False),sa.Column('description',sa.Text()),sa.Column('video_path',sa.String(1024)),sa.Column('slides_path',sa.String(1024)),sa.Column('duration_seconds',sa.Integer()),sa.Column('is_public',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now())); op.create_index('ix_lectures_owner_id','lectures',['owner_id'])
    op.create_table('tokens',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('token_hash',sa.String(128),nullable=False),sa.Column('token_type',sa.String(32),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('revoked_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now())); op.create_index('ix_tokens_user_id','tokens',['user_id']); op.create_index('ix_tokens_token_hash','tokens',['token_hash'],unique=True); op.create_index('ix_tokens_token_type','tokens',['token_type']); op.create_index('ix_tokens_expires_at','tokens',['expires_at'])
def downgrade():
    op.drop_table('tokens'); op.drop_table('lectures'); op.drop_table('users')
